languageCode = "en"
languageName = "English"
title = "kahakai"
weight = 1

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "Personal blog about life-related and development-related things."
madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
