[[main]]
name = "About"
pageRef = "about"
weight = 1

[[main]]
name = "Blog"
pageRef = "posts"
weight = 2

[[main]]
name = "Talks"
pageRef = "talks"
weight = 3

[[main]]
name = "Projects"
pageRef = "projects"
weight = 4
